import { StyleSheet } from 'react-native';

// Paleta "operaciones diurnas" (light) y "operaciones nocturnas" (dark)
export const LIGHT_COLORS = {
  bg: '#EDE9DC',
  card: '#F7F4E9',
  primary: '#4B5320',
  accent: '#B8862E',
  text: '#242018',
  textMuted: '#7A745F',
  bubbleMine: '#4B5320',
  bubbleTheirs: '#DCD6C1',
  border: '#B9B196',
  danger: '#8C2F1E',
};

export const DARK_COLORS = {
  bg: '#15170F',
  card: '#20231A',
  primary: '#6B7A3A',
  accent: '#D4A24C',
  text: '#EDEAD9',
  textMuted: '#8C917A',
  bubbleMine: '#4B5320',
  bubbleTheirs: '#2B2E22',
  border: '#3A3E2C',
  danger: '#C0432E',
};

export type Colors = typeof LIGHT_COLORS;

export function createStyles(COLORS: Colors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    authWrapper: { flex: 1, backgroundColor: '#4B5320' },
    authCard: {
      flex: 1,
      backgroundColor: COLORS.bg,
      marginTop: 90,
      paddingHorizontal: 26,
      paddingTop: 32,
      alignItems: 'center',
      borderTopWidth: 3,
      borderTopColor: COLORS.accent,
    },
    logoBadge: {
      width: 66, height: 66, borderRadius: 10,
      backgroundColor: COLORS.primary,
      alignItems: 'center', justifyContent: 'center',
      marginTop: -70,
      marginBottom: 14,
      borderWidth: 2,
      borderColor: COLORS.accent,
    },
    logoText: { fontSize: 30 },
    appName: { fontSize: 22, fontWeight: '800', color: COLORS.text, letterSpacing: 3 },
    appNameUnderline: { width: 40, height: 3, backgroundColor: COLORS.accent, marginTop: 8, marginBottom: 12 },
    appTagline: { fontSize: 12, color: COLORS.textMuted, marginBottom: 20, textAlign: 'center', lineHeight: 17, fontStyle: 'italic' },
    connectionPill: {
      flexDirection: 'row', alignItems: 'center',
      backgroundColor: COLORS.card, borderRadius: 3,
      paddingHorizontal: 12, paddingVertical: 6, marginBottom: 22,
      borderWidth: 1, borderColor: COLORS.border,
    },
    dot: { width: 7, height: 7, borderRadius: 4, marginRight: 7 },
    connectionText: { fontSize: 10, color: COLORS.textMuted, letterSpacing: 1, fontWeight: '700' },
    formTitle: { fontSize: 13, fontWeight: '800', color: COLORS.accent, alignSelf: 'flex-start', marginBottom: 16, letterSpacing: 1.5 },
    inputLabel: { fontSize: 10, fontWeight: '700', color: COLORS.textMuted, alignSelf: 'flex-start', letterSpacing: 1, marginBottom: 4 },
    input: {
      width: '100%', backgroundColor: COLORS.card,
      borderRadius: 2, padding: 12, fontSize: 15, color: COLORS.text,
      marginBottom: 14, borderWidth: 1, borderColor: COLORS.border,
    },
    errorText: { color: COLORS.danger, fontSize: 12, marginBottom: 10, alignSelf: 'flex-start', fontWeight: '600' },
    primaryButton: {
      width: '100%', backgroundColor: COLORS.accent,
      borderRadius: 2, paddingVertical: 14, alignItems: 'center', marginTop: 6,
    },
    primaryButtonText: { color: '#1A1712', fontWeight: '800', fontSize: 14, letterSpacing: 1.5 },
    switchText: { color: COLORS.textMuted, marginTop: 18, fontSize: 11, letterSpacing: 0.5 },
    switchTextBold: { color: COLORS.accent, fontWeight: '800' },
    recoveryCodeBox: {
      width: '100%', backgroundColor: COLORS.card, borderWidth: 2, borderColor: COLORS.accent,
      borderRadius: 3, paddingVertical: 20, alignItems: 'center', marginBottom: 24,
    },
    recoveryCodeText: { fontSize: 26, fontWeight: '800', color: COLORS.accent, letterSpacing: 4 },
    header: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 14, backgroundColor: COLORS.card, borderBottomWidth: 2, borderBottomColor: COLORS.primary },
    headerRow: { flexDirection: 'row', alignItems: 'center' },
    headerTitle: { fontSize: 15, fontWeight: '800', color: COLORS.text, letterSpacing: 1 },
    headerSubtitle: { fontSize: 10, color: COLORS.textMuted, marginTop: 2, fontWeight: '600', letterSpacing: 0.5 },
    logoutButton: {
      borderWidth: 1, borderColor: COLORS.border, borderRadius: 2,
      paddingHorizontal: 10, paddingVertical: 6,
    },
    logoutButtonText: { fontSize: 10, fontWeight: '800', color: COLORS.danger, letterSpacing: 1 },
    selfDestructActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
    sectionDivider: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 8 },
    sectionTitle: { fontSize: 10, fontWeight: '800', color: COLORS.textMuted, letterSpacing: 1.5 },
    userRow: {
      flexDirection: 'row', alignItems: 'center',
      backgroundColor: COLORS.card, borderRadius: 3,
      padding: 12, marginBottom: 8,
      borderWidth: 1, borderColor: COLORS.border,
      borderLeftWidth: 3, borderLeftColor: COLORS.primary,
    },
    userName: { fontSize: 13, fontWeight: '700', color: COLORS.text, letterSpacing: 0.5 },
    userStatus: { fontSize: 10, color: COLORS.textMuted, marginTop: 2, fontWeight: '600', letterSpacing: 0.5 },
    chevron: { fontSize: 22, color: COLORS.textMuted },
    statusDot: {
      position: 'absolute', bottom: -2, right: -2,
      width: 12, height: 12, borderRadius: 3,
      borderWidth: 2, borderColor: COLORS.bg,
    },
    emptyState: { alignItems: 'center', marginTop: 60 },
    emptyEmoji: { fontSize: 32, marginBottom: 8 },
    emptyText: { color: COLORS.textMuted, fontSize: 11, fontWeight: '700', letterSpacing: 1 },
    chatHeader: {
      flexDirection: 'row', alignItems: 'center',
      paddingHorizontal: 12, paddingVertical: 10,
      backgroundColor: COLORS.card, borderBottomWidth: 2, borderBottomColor: COLORS.primary,
    },
    backTouchable: { paddingRight: 6, paddingVertical: 4 },
    backChevron: { fontSize: 30, color: COLORS.accent, fontWeight: '300' },
    chatHeaderName: { fontSize: 14, fontWeight: '800', color: COLORS.text, letterSpacing: 0.5 },
    chatHeaderSub: { fontSize: 10, color: COLORS.textMuted, marginTop: 1, fontWeight: '600', letterSpacing: 0.3 },
    messageList: { padding: 14, paddingBottom: 10 },
    bubble: { maxWidth: '80%', paddingHorizontal: 14, paddingVertical: 9, borderRadius: 18 },
    imageBubble: { padding: 4, overflow: 'hidden' },
    messageImage: { width: 220, height: 220, borderRadius: 14 },
    myBubble: { backgroundColor: COLORS.bubbleMine, borderTopRightRadius: 5 },
    theirBubble: { backgroundColor: COLORS.bubbleTheirs, borderTopLeftRadius: 5, borderWidth: 1, borderColor: COLORS.border },
    myText: { color: '#F2F0E4', fontSize: 15, lineHeight: 20 },
    theirText: { color: COLORS.text, fontSize: 15, lineHeight: 20 },
    myLinkText: { color: '#F2F0E4', fontSize: 15, lineHeight: 20, textDecorationLine: 'underline', fontWeight: '700' },
    theirLinkText: { color: COLORS.accent, fontSize: 15, lineHeight: 20, textDecorationLine: 'underline', fontWeight: '700' },
    timestamp: { fontSize: 9, color: COLORS.textMuted, marginTop: 3, marginHorizontal: 4, fontWeight: '600' },
    checkmark: { fontSize: 10, color: COLORS.textMuted, marginTop: 3, fontWeight: '700' },
    checkmarkRead: { color: COLORS.accent },
    checkmarkFailed: { fontSize: 10, color: COLORS.danger, marginTop: 3, marginLeft: 6, fontWeight: '800' },
    inputRow: {
      flexDirection: 'row', alignItems: 'flex-end',
      paddingHorizontal: 12, paddingVertical: 10,
      backgroundColor: COLORS.card, borderTopWidth: 2, borderTopColor: COLORS.primary,
    },
    messageInput: {
      flex: 1, backgroundColor: COLORS.bg,
      borderRadius: 2, paddingHorizontal: 14, paddingVertical: 10,
      fontSize: 15, color: COLORS.text, maxHeight: 100, marginRight: 8,
      borderWidth: 1, borderColor: COLORS.border,
    },
    sendButton: {
      width: 42, height: 42, borderRadius: 3,
      backgroundColor: COLORS.accent, alignItems: 'center', justifyContent: 'center',
    },
    sendButtonIcon: { color: '#1A1712', fontSize: 16, fontWeight: '800' },
    attachButton: {
      width: 42, height: 42, borderRadius: 3,
      backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border,
      alignItems: 'center', justifyContent: 'center', marginRight: 8,
    },
    attachButtonIcon: { fontSize: 18 },
    attachButtonRecording: { backgroundColor: COLORS.danger, borderColor: COLORS.danger },
    recordingIndicator: {
      flex: 1, flexDirection: 'row', alignItems: 'center',
      backgroundColor: COLORS.bg, borderRadius: 2,
      paddingHorizontal: 14, paddingVertical: 10, marginRight: 8,
      borderWidth: 1, borderColor: COLORS.danger,
    },
    recordingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.danger, marginRight: 8 },
    recordingText: { flex: 1, color: COLORS.text, fontSize: 15, fontWeight: '600' },
    stickerText: { fontSize: 72 },
    stickerPanel: {
      backgroundColor: COLORS.card, borderTopWidth: 2, borderTopColor: COLORS.primary,
      paddingVertical: 10, paddingHorizontal: 8, maxHeight: 160,
    },
    stickerOption: {
      flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 8,
    },
    stickerOptionText: { fontSize: 30 },

    // Encabezado del chat, con el mismo estilo que la barra de escritura
    topRow: {
      flexDirection: 'row', alignItems: 'center',
      paddingHorizontal: 8, paddingTop: 6, paddingBottom: 6,
      backgroundColor: COLORS.bg,
    },
    topBox: {
      flex: 1, flexDirection: 'row', alignItems: 'center',
      height: 50, backgroundColor: COLORS.card,
      borderRadius: 25, borderWidth: 1, borderColor: COLORS.border,
      paddingRight: 14, marginRight: 6,
    },
    topBack: { width: 36, height: 48, alignItems: 'center', justifyContent: 'center' },
    topBackIcon: { fontSize: 30, color: COLORS.accent, fontWeight: '300', marginTop: -3 },
    topContact: { flex: 1, flexDirection: 'row', alignItems: 'center' },
    topName: { fontSize: 16, fontWeight: '700', color: COLORS.text },
    topSub: { fontSize: 11, color: COLORS.textMuted, marginTop: 1 },
    topRoundButton: {
      width: 46, height: 46, borderRadius: 23, marginLeft: 4,
      backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border,
      alignItems: 'center', justifyContent: 'center',
    },
    topRoundButtonActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
    topRoundIcon: { fontSize: 18 },
    topRoundTextActive: { fontSize: 14, color: '#F2F0E4', fontWeight: '800' },
    topSearchRow: { paddingHorizontal: 8, paddingBottom: 6, backgroundColor: COLORS.bg },
    topSearchInput: {
      height: 44, backgroundColor: COLORS.card, borderRadius: 22, borderWidth: 1, borderColor: COLORS.border,
      paddingHorizontal: 16, fontSize: 15, color: COLORS.text,
    },

    // Barra de escritura estilo WhatsApp
    composerRow: {
      flexDirection: 'row', alignItems: 'flex-end',
      paddingHorizontal: 8, paddingTop: 6, paddingBottom: 8,
      backgroundColor: COLORS.bg,
    },
    composerBox: {
      flex: 1, flexDirection: 'row', alignItems: 'center',
      minHeight: 46, backgroundColor: COLORS.card,
      borderRadius: 23, borderWidth: 1, borderColor: COLORS.border,
      paddingLeft: 16, paddingRight: 4, marginRight: 6,
    },
    composerInput: {
      flex: 1, fontSize: 16, color: COLORS.text,
      paddingTop: 11, paddingBottom: 11, maxHeight: 120,
    },
    composerIconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    composerIcon: { fontSize: 20 },
    composerAction: {
      width: 46, height: 46, borderRadius: 23,
      backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center',
    },
    composerActionRecording: { backgroundColor: COLORS.danger },
    composerActionIcon: { fontSize: 19, color: '#F2F0E4', fontWeight: '800' },

    systemRow: { alignItems: 'center', marginVertical: 8, paddingHorizontal: 24 },
    systemText: {
      fontSize: 11, color: COLORS.textMuted, textAlign: 'center',
      backgroundColor: COLORS.card, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border,
      paddingHorizontal: 12, paddingVertical: 6, overflow: 'hidden',
    },
    quoteBox: {
      borderLeftWidth: 3, borderLeftColor: COLORS.accent, borderRadius: 10,
      backgroundColor: 'rgba(0,0,0,0.12)', paddingHorizontal: 10, paddingVertical: 6, marginBottom: 6,
    },
    quoteName: { fontSize: 10, fontWeight: '800', color: COLORS.accent, letterSpacing: 0.5 },
    quoteText: { fontSize: 12, color: COLORS.textMuted },
    quoteTextMine: { fontSize: 12, color: '#D9D6C6' },
    replyBar: {
      flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.card,
      borderTopWidth: 1, borderTopColor: COLORS.border, paddingHorizontal: 12, paddingVertical: 8,
    },
    replyBarLabel: { fontSize: 10, fontWeight: '800', color: COLORS.accent, letterSpacing: 1 },
    replyBarText: { fontSize: 12, color: COLORS.text, marginTop: 2 },
    replyBarClose: { fontSize: 18, color: COLORS.textMuted, paddingHorizontal: 8 },
    editedLabel: { fontSize: 9, color: COLORS.textMuted, marginTop: 3, fontStyle: 'italic' },
    deletedText: { fontSize: 13, fontStyle: 'italic', color: COLORS.textMuted },
    reactionsRow: { flexDirection: 'row', marginTop: -4, marginHorizontal: 6 },
    reactionChip: {
      backgroundColor: COLORS.card, borderRadius: 10, borderWidth: 1, borderColor: COLORS.border,
      paddingHorizontal: 6, paddingVertical: 1, marginRight: 4,
    },
    reactionText: { fontSize: 13 },
    banner: { backgroundColor: COLORS.danger, paddingHorizontal: 14, paddingVertical: 10 },
    bannerText: { color: '#F2F0E4', fontSize: 12, fontWeight: '600', lineHeight: 17 },
    bannerButtons: { flexDirection: 'row', marginTop: 8 },
    bannerButton: { borderWidth: 1, borderColor: '#F2F0E4', borderRadius: 2, paddingHorizontal: 10, paddingVertical: 5, marginRight: 8 },
    bannerButtonText: { color: '#F2F0E4', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 24 },
    modalCard: { backgroundColor: COLORS.bg, borderRadius: 4, padding: 18, borderTopWidth: 3, borderTopColor: COLORS.accent },
    modalTitle: { fontSize: 13, fontWeight: '800', color: COLORS.accent, letterSpacing: 1.5, marginBottom: 12 },
    modalText: { fontSize: 13, color: COLORS.text, marginBottom: 12, lineHeight: 18 },
    modalOption: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    modalOptionText: { fontSize: 14, color: COLORS.text, fontWeight: '600' },
    modalDangerText: { fontSize: 14, color: COLORS.danger, fontWeight: '700' },
    modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 8 },
    modalButton: { paddingHorizontal: 14, paddingVertical: 10, marginLeft: 8 },
    modalButtonText: { fontSize: 12, fontWeight: '800', color: COLORS.accent, letterSpacing: 1 },
    emojiRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    emojiOption: { fontSize: 28, padding: 4 },
    searchBar: {
      flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.card,
      paddingHorizontal: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.border,
    },
    searchInput: {
      flex: 1, backgroundColor: COLORS.bg, borderRadius: 2, paddingHorizontal: 12, paddingVertical: 8,
      fontSize: 14, color: COLORS.text, borderWidth: 1, borderColor: COLORS.border,
    },
    headerIconButton: { paddingHorizontal: 8, paddingVertical: 6 },
    headerIconText: { fontSize: 18 },
    unreadBadge: {
      minWidth: 20, height: 20, borderRadius: 10, backgroundColor: COLORS.accent,
      alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, marginRight: 8,
    },
    unreadBadgeText: { fontSize: 11, fontWeight: '800', color: '#1A1712' },
    warningText: { fontSize: 10, color: COLORS.danger, marginTop: 2, fontWeight: '800', letterSpacing: 0.5 },
    verifiedText: { fontSize: 10, color: COLORS.primary, marginTop: 2, fontWeight: '800', letterSpacing: 0.5 },
    screenBody: { padding: 16 },
    infoSectionTitle: { fontSize: 10, fontWeight: '800', color: COLORS.textMuted, letterSpacing: 1.5, marginTop: 18, marginBottom: 8 },
    infoText: { fontSize: 13, color: COLORS.text, lineHeight: 19 },
    safetyGrid: { flexDirection: 'row', flexWrap: 'wrap', backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border, padding: 12, borderRadius: 3 },
    safetyGroup: { width: '25%', fontSize: 17, fontWeight: '700', color: COLORS.text, textAlign: 'center', paddingVertical: 6, letterSpacing: 1 },
    secondaryButton: {
      width: '100%', borderWidth: 1, borderColor: COLORS.border, borderRadius: 2,
      paddingVertical: 12, alignItems: 'center', marginTop: 10, backgroundColor: COLORS.card,
    },
    secondaryButtonText: { color: COLORS.text, fontWeight: '800', fontSize: 12, letterSpacing: 1 },
    dangerButtonText: { color: COLORS.danger, fontWeight: '800', fontSize: 12, letterSpacing: 1 },
    settingsRow: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border, borderRadius: 3, padding: 12, marginBottom: 8,
    },
    settingsLabel: { fontSize: 13, fontWeight: '700', color: COLORS.text },
    settingsHint: { fontSize: 11, color: COLORS.textMuted, marginTop: 2 },
    lockScreen: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#4B5320', alignItems: 'center', justifyContent: 'center', padding: 32 },
    lockTitle: { fontSize: 18, fontWeight: '800', color: '#F2F0E4', letterSpacing: 3, marginVertical: 16 },
    mediaPlaceholder: { width: 220, height: 120, alignItems: 'center', justifyContent: 'center' },
    mediaPlaceholderText: { fontSize: 12, color: COLORS.textMuted, textAlign: 'center', paddingHorizontal: 12 },
    mediaPlaceholderTextMine: { fontSize: 12, color: '#D9D6C6', textAlign: 'center', paddingHorizontal: 12 },
  });
}
